apiVersion: v1
kind: Service
metadata:
  name: svc-web
  namespace: mgtest
spec:
  type: NodePort
  selector:
    app: nyfd-web
  ports:
  - name: mgport
    port: 80
    targetPort: 80
    nodePort: 30083

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nyfd-web
  name: dp-nyfd-web
  namespace: mgtest
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nyfd-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nyfd-web
    spec:
      containers:
        - image: ${Web}
          imagePullPolicy: IfNotPresent
          name: dp-nyfd-web
          ports:
            - containerPort: 80
              protocol: TCP

---